/**
 * Contract test for Question Author candidate questions generated by agent workflows.
 *
 * Verifies that candidate objects pass both:
 * 1. mctl-academy's JSON schema validator (question.schema.json)
 * 2. mctl-academy's R2 evidence verifier (verifyEvidence) against real R2 snapshot text.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import Ajv from "ajv/dist/2020.js";
import addFormats from "ajv-formats";

import { verifyEvidence } from "../scripts/verify-evidence.mjs";

const sha256 = (s) => createHash("sha256").update(Buffer.from(s, "utf8")).digest("hex");

const SAMPLE_SNAPSHOT_DOC =
  "Function calling allows LLMs to return JSON structured data matching a tool schema for agentic workflows.";
const SNAPSHOT_SHA256 = sha256(SAMPLE_SNAPSHOT_DOC);

const ROOT = new URL("..", import.meta.url).pathname;
const QUESTION_SCHEMA_PATH = join(ROOT, "content", "schemas", "question.schema.json");
const questionSchema = JSON.parse(readFileSync(QUESTION_SCHEMA_PATH, "utf8"));

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);
const validateQuestionSchema = ajv.compile(questionSchema);

/** In-memory stand-in for the R2 store. */
const fakeStore = (objects) => ({
  async get(key) {
    if (!(key in objects)) return null;
    if (objects[key] instanceof Error) throw objects[key];
    return objects[key];
  },
});

function createTempContentTree({ sourceObj, questionObj }) {
  const dir = mkdtempSync(join(tmpdir(), "academy-author-contract-"));
  mkdirSync(join(dir, "sources"), { recursive: true });
  mkdirSync(join(dir, "questions"), { recursive: true });
  writeFileSync(join(dir, "sources", `${sourceObj.id}.yaml`), JSON.stringify(sourceObj, null, 2));
  writeFileSync(join(dir, "questions", `${questionObj.id}.yaml`), JSON.stringify(questionObj, null, 2));
  return dir;
}

const mockSource = {
  schema_version: 1,
  id: "src-function-calling",
  url: "https://docs.nebius.com/function-calling.md",
  title: "Function Calling Docs",
  retrieved_at: "2026-08-09T10:00:00Z",
  sha256: SNAPSHOT_SHA256,
  objectives: ["domain-2/function-calling"],
  snapshot: { bucket: "academy-source-snapshots", key: SNAPSHOT_SHA256 },
};

/** Sample author_question candidate payload matching mctl-agents output contract */
const sampleAuthorCandidate = () => ({
  schema_version: 1,
  id: "q-a1b2c3d4e5f6",
  course_id: "agentic-ai-builder",
  status: "review_ready",
  domain: "domain-2",
  objective: "domain-2/function-calling",
  stem: "What capability allows LLMs to return JSON structured data matching a tool schema?",
  options: [
    {
      id: "a",
      text: "Function calling capability",
      correct: true,
      explanation:
        "Function calling allows LLMs to return structured JSON data according to defined tool schemas.",
    },
    {
      id: "b",
      text: "Plain text streaming",
      correct: false,
      explanation: "Plain text streaming does not structure outputs according to JSON tool schemas.",
    },
    {
      id: "c",
      text: "Binary RPC protocol",
      correct: false,
      explanation: "Binary RPC is not the mechanism used for JSON schema matching in LLMs.",
    },
    {
      id: "d",
      text: "Manual regex parsing",
      correct: false,
      explanation: "Manual regex parsing is prone to errors and is not native function calling.",
    },
  ],
  evidence: [
    {
      source_id: "src-function-calling",
      source_sha256: SNAPSHOT_SHA256,
      excerpt: "Function calling allows LLMs to return JSON structured data matching a tool schema",
    },
  ],
  authored: {
    by: "agent:question-author",
    at: "2026-08-09T12:00:00Z",
  },
});

test("question-author candidate passes question.schema.json validation", () => {
  const candidate = sampleAuthorCandidate();
  const valid = validateQuestionSchema(candidate);
  assert.equal(valid, true, `Schema validation failed: ${JSON.stringify(validateQuestionSchema.errors)}`);
});

test("question-author candidate passes evidence verification against R2 snapshot store", async () => {
  const candidate = sampleAuthorCandidate();
  const dir = createTempContentTree({ sourceObj: mockSource, questionObj: candidate });

  try {
    const store = fakeStore({ [SNAPSHOT_SHA256]: SAMPLE_SNAPSHOT_DOC });
    const { errors, checked } = await verifyEvidence({ contentDir: dir, store });
    assert.deepEqual(errors, []);
    assert.equal(checked, 1);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("evidence verification rejects candidate when excerpt is not found in R2 snapshot", async () => {
  const candidate = sampleAuthorCandidate();
  candidate.evidence[0].excerpt = "Function calling allows models to execute arbitrary shell commands"; // Fabricated text

  const dir = createTempContentTree({ sourceObj: mockSource, questionObj: candidate });

  try {
    const store = fakeStore({ [SNAPSHOT_SHA256]: SAMPLE_SNAPSHOT_DOC });
    const { errors } = await verifyEvidence({ contentDir: dir, store });
    assert.equal(errors.length, 1);
    assert.match(errors[0], /not found verbatim/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("evidence verification rejects candidate when R2 snapshot sha256 does not match source snapshot key", async () => {
  const candidate = sampleAuthorCandidate();
  const invalidSha = "b".repeat(64);
  candidate.evidence[0].source_sha256 = invalidSha;

  const dir = createTempContentTree({ sourceObj: mockSource, questionObj: candidate });

  try {
    const store = fakeStore({ [SNAPSHOT_SHA256]: SAMPLE_SNAPSHOT_DOC });
    const { errors } = await verifyEvidence({ contentDir: dir, store });
    assert.equal(errors.length, 1);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
