import rawBundle from "../content-bundle.json";

/**
 * The published question bank, as generated by
 * scripts/build-content-bundle.mjs.
 *
 * Everything in this file is safe to show a learner by construction: the build
 * step only emits questions that are published, human-reviewed, and cite
 * sources that exist, are snapshotted, and are neither drifted nor deprecated.
 * There is deliberately no runtime evidence check anywhere in the client — if
 * a source drifts, the operational action is to mark it in content/ and
 * rebuild, not to hope a browser fetch succeeds.
 */
export interface BundleOption {
  id: string;
  text: string;
  correct: boolean;
  explanation: string;
}

export interface BundleQuestion {
  id: string;
  /** Canonical course membership, from content/questions/*.yaml. */
  course_id: string;
  domain: string;
  objective: string;
  stem: string;
  options: BundleOption[];
}

export const allQuestions = rawBundle as unknown as readonly BundleQuestion[];

/**
 * The bank scoped to one course. Every learning surface — practice, mistakes,
 * dashboard, mock — starts from this, which is why none of them can mix
 * courses: a question's course membership is content metadata, never learner
 * state.
 */
export function questionsForCourse(courseId: string | null): BundleQuestion[] {
  if (!courseId) return [];
  return allQuestions.filter((q) => q.course_id === courseId);
}

/** Question ids belonging to a course, for intersecting against attempts. */
export function questionIdsForCourse(courseId: string | null): Set<string> {
  return new Set(questionsForCourse(courseId).map((q) => q.id));
}
