import rawBundle from "../content-bundle.json";
import type { OptionId } from "../exam/types";

/**
 * The published question bank, as generated by
 * scripts/build-content-bundle.mjs.
 *
 * Everything in this file is safe to show a learner by construction: the build
 * step only emits questions that are published, human-reviewed, and cite
 * sources that exist, are snapshotted, and are neither drifted nor deprecated.
 * There is deliberately no runtime evidence check anywhere in the client — if
 * a source drifts, the operational action is to mark it in content/ and
 * rebuild, not to hope a browser fetch succeeds.
 */
export interface BundleOption {
  /**
   * Narrowed to the same union the exam types use, not left as `string`.
   * scripts/lib/validate-generated-artifacts.mjs fails the build if the
   * emitted bundle ever carries an option id outside it, which is what lets
   * Practice and Mock share one option type instead of casting between two
   * that differ only here.
   */
  id: OptionId;
  text: string;
  correct: boolean;
  explanation: string;
}

export interface BundleQuestion {
  id: string;
  /** Canonical course membership, from content/questions/*.yaml. */
  course_id: string;
  domain: string;
  objective: string;
  stem: string;
  options: BundleOption[];
}

/**
 * The single assertion of the build-time contract into the type system.
 *
 * TypeScript infers the imported JSON structurally (option `id` widens to
 * `string`), and the client deliberately runs no runtime validator — see
 * CLAUDE.md. What makes this cast true rather than hopeful is
 * scripts/lib/validate-generated-artifacts.mjs, which the bundle builder runs
 * before writing either file, so a bundle that does not match this shape
 * fails the build instead of reaching the browser.
 */
export const allQuestions = rawBundle as unknown as readonly BundleQuestion[];

/**
 * The bank scoped to one course. Every learning surface — practice, mistakes,
 * dashboard, mock — starts from this, which is why none of them can mix
 * courses: a question's course membership is content metadata, never learner
 * state.
 */
export function questionsForCourse(courseId: string | null): BundleQuestion[] {
  if (!courseId) return [];
  return allQuestions.filter((q) => q.course_id === courseId);
}

/** Question ids belonging to a course, for intersecting against attempts. */
export function questionIdsForCourse(courseId: string | null): Set<string> {
  return new Set(questionsForCourse(courseId).map((q) => q.id));
}
